### ISSUE TITLE
Nil Map when unmarshalling Json

### ISSUE THREAD

**Issue by victorddiniz** [inloco/kafka-elasticsearch-injector#9]
On function [`JsonMessageToRecord`](https://github.com/inloco/kafka-elasticsearch-injector/blob/master/src/kafka/encode_decode.go#L93), the `msg.Value` may be a JSON literal null. In that case, according to [Go's documentation](https://golang.org/pkg/encoding/json/#Unmarshal):
 
> Unmarshal first handles the case of the JSON being the JSON literal null. In that case, Unmarshal sets the pointer to nil

Given that, `jsonValue` will be a nil map and you [cannot write any value to nil map](https://blog.golang.org/go-maps-in-action).

It would be better to handle any errors before writing any values to the map and also to check if the map is not nil, as JSON literal null is a valid input.

**Comment by racevedoo** [comment]
Fixed on 1.1.3. Thanks!
